locators/base_page_locators.py, pages/main_page.py, tests/test_main_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;99qaGhm7">TC__001.001.01 | Main page &gt; Self &gt;Verify visability the title, logo “Luma” at the top of the page</a>
=> AT__001.001.01 | Main page > Self >Verify visability the title, logo “Luma” at the top of the page

locators/base_page_locators.py, pages/main_page.py, tests/test_main_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YzxHzpFG">TC_001.002.01 | Main page &gt; Search Erin recommends widget &gt;Visibility of Erin recommends widget</a></blockquote>
=> TC/AT_001.002.01 | Main page > Search Erin recommends widget >Visibility of Erin recommends widget

locators/base_page_locators.py, pages/main_page.py, tests/test_main_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gS7q5aXp">TC_001.002.02 | Main page &gt; Search Erin recommends widget &gt;Сlickability of &#39;Erin recommends&#39; widget</a></blockquote>
=> TC/AT_001.002.02 | Main page > Search Erin recommends widget >Сlickability of 'Erin recommends' widget

locators/training_page_locators.py, pages/training_page/training_page.py, tests/training_page/test_training_page.py
https://trello.com/c/GTDmLs5i/165-tc010001001-traning-visibility-verify-opening-traning-page
=> add test_open_Training_page related to TC_010.001.001

data/men_page_url.py, locators/men_page_locators.py, pages/men_page.py, tests/test_men_page.py
https://trello.com/c/VcZpKaKt
https://trello.com/c/3ZLRkdBM
=> TC_008.003.001 and TC_008.003.002

locators/product_page_locators.py, tests/product_page/test_product_page_structure.py
[TC_002.002.001 | Product page > Self > Structure > Checking page structure](https://trello.com/c/YxI5ascy/440-tc002002001-product-page-self-structure-checking-page-structure)
=> add: TC_002.002.001

data/product_page_data.py, locators/product_page_locators.py, tests/product_page/test_product_page_body_structure.py, tests/product_page/test_product_page_structure.py
[TC_002.003.001](https://trello.com/c/AFuYMnCB/441-tc002003001-product-page-body-structure-checking-the-product-page-body-structure)
=> TC_002.003.001

data/popular_search_terms_page_data.py, locators/popular_search_terms_page_locators.py, pages/popular_search_terms/popular_search_terms_page.py, tests/popular_search_terms/test_content_popular_search_terms_page.py
[TC_015.001.002](https://trello.com/c/67MNuYaD/265-tc015001002-popular-search-terms-content-verify-the-heading-on-the-popular-search-terms-page)
https://trello.com/c/67MNuYaD/265-tc015001002-popular-search-terms-content-verify-the-heading-on-the-popular-search-terms-page
=> TC_015.001.002 | Popular Search Terms > Content > Verify the heading on the Popular Search Terms Page

data/men_page_url.py, locators/men_page_locators.py, pages/men_page.py, tests/test_men_page.py
=> TC_008.010.01

tests/gear_page/test_gear_page.py
Hi, TCs from Trello as well
https://trello.com/c/rLv54OwV/158-tc009001001-gear-page-categories-shop-by-category
https://trello.com/c/uRTVHCRJ/162-tc009001002-gear-page-categories-category-bags - and the other two are similar 
https://trello.com/c/HySfjBo4/161-tc009002001-gear-page-categories-the-counter-for-the-category-bags and for other Categories
https://trello.com/c/sqWEnKkE/174-tc009002004-gear-page-categories-verify-the-counter-on-the-gear-page-for-the-category-bags-with-counter-on-the-category-page and for other Categories
=> TC_009.001.001 - TC_009.002.006

locators/gear_page_locators.py, tests/gear_page/test_gear_page_evg.py
TC:
https://trello.com/c/HVDo2q8b/217-tc009003001-gear-page-categories-visibility-of-the-sprite-yoga-companion-kit-banner
=> Test gear page evg

tests/footer/test_verification_footer_elements.py
https://trello.com/c/SgonG9Je/404-tc012001001-footer-write-for-us-link-verify-visibility-of-the-link-for-the-page-for-writing-an-article
https://trello.com/c/2pVgBszn/405-tc012001002-footer-write-for-us-link-verify-clickability-of-the-link-for-the-page-for-writing-an-article
https://trello.com/c/BT0NUsoV/453-tc012011001-footer-self-verify-copyright-statement-in-the-footer
https://trello.com/c/oRFeXw5I/457-tc012011002-footer-self-text-verification-of-copyright-information
=> TC_012.001.001-002, TC_012.011.001-002

base/seleniumbase.py, locators/popular_search_terms_page_locators.py, pages/popular_search_terms/popular_search_terms_page.py, tests/popular_search_terms/test_content_popular_search_terms_page.py
[TC_015.001.003](https://trello.com/c/qkthDsnb/268-tc015001003-popular-search-terms-content-verify-the-number-of-keywords-on-the-popular-search-terms-page)
=>  TC_015.001.003 | Popular Search Terms > Content > Verify the number of keywords on the Popular Search Terms page

data/men_page_url.py, locators/men_page_locators.py, pages/men_page.py, tests/test_men_page.py
=> TC_008.022.001 | Redirected to Bottoms page from Men dropdown button

pages/other_pages/what_is_new.py, tests/what_is_new_page/test_what_is_new_page.py
=> def test_widget_subtitle

tests/product_page/test_product_name_in_page_title.py
[TC_002.001.003 | Product page > Title > Product name in the page title](https://trello.com/c/TuvVv4eh/499-tc002001003-product-page-title-product-name-in-the-page-title)
=> Refactor: fix test description

locators/training_page_locators.py, pages/training_page/traning_page.py, tests/training_page/test_training_page.py
TC_010.003.001
https://trello.com/c/kHmozDIA/170-tc010003001-traning-category-video-download-redirection-verify-that-the-video-download-link-is-clickable
=> add test_Video_Download_is_clickable related to TC_010.003.001

data/product_page_data.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
[TC_002.005.001 | Product page > Body > Main info >Name](https://trello.com/c/9oAwAc7n/148-tc002005001-product-page-body-main-info-name)
=> TC_002.005.001 | Product page > Body > Main info >Name

locators/base_page_locators.py, pages/main_page.py, pages/performance_fabrics/performance_fabrics.py, tests/test_main_page.py
TC_001.003.001 
https://trello.com/c/42v04NBl/195-tc001003001-main-page-search-shop-performance-widget-clickability-verify-that-widget-shop-performance-is-clickable
TC_001.002.001 
https://trello.com/c/z5fZtD2k/236-tc001002001-main-page-search-erin-recommends-widget-visibility-verify-that-widget-erin-recommends-is-visible
=> add test_main_page_erin_recommends_is_visible and test_main_page_shop_performance_is_clickable

pages/other_pages/eco_collection_new.py, tests/eco_collection_new_page/test_collection_page.py, tests/login/test__sign_in.py
TC _006.013.001, TC _006.013.002, TC _006.013.003v
=> def test_title_page, def test_banner_title, def test_bunner_subtitle

data/product_page_data.py, locators/product_page_locators.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
[TC_002.005.002 | Product page > Body > Main info > Rating block](https://trello.com/c/CjAOBLZI/149-tc002005002-product-page-body-main-info-rating-block)
=> Add test for TC_002.005.002 Product page>Body>Main info>Rating block

pages/gear_page/gear_page.py, tests/gear_page/conftest.py, tests/gear_page/test_gear_page.py
Removed some part of driver initialization(working only with collecting test data) to the gear_page conftest (don't know how to perform it better for now), If you have an idea where it should be placed or another version of performing, hit me up, thank you
this is not urgent
=> removing spaces, adding additional method(all for gear page)

pages/training_page/traning_page.py, tests/training_page/test_training_page.py
TC_010.003.002
https://trello.com/c/TZ3UFa9i/176-tc010003002-traning-category-video-download-redirection-redirection-to-the-video-download-page
=> add test_redirect_to_video_download_page related to TC_010.003.002

tests/product_page/test_product_page_body_structure.py
убрал вот это вот:
tests/product_page/test_product_page_body_structure.py::test_product_page_body_structure[https://magento.softwaretestingboard.com/juno-jacket.html] An error occurred: Message: 
Stacktrace:
#0 0x562bd2fa15e3 <unknown>
#1 0x562bd2c640b7 <unknown>
#2 0x562bd2cb1f53 <unknown>
#3 0x562bd2cb2051 <unknown>
#4 0x562bd2cf79c4 <unknown>
#5 0x562bd2cd8f1d <unknown>
#6 0x562bd2cf4b3d <unknown>
#7 0x562bd2cd8cc3 <unknown>
=> [!] так лучше

tests/product_page/test_product_page_body_structure.py
[TC_002.003.003 | Product page > DOM > Body structure](https://trello.com/c/DW2m0Lcz/501-tc002003003-product-page-dom-body-structure)
add MIN_TIMEOUT to reduce total test time
=> Small fix TC_002.003.003

base/seleniumbase.py, tests/training_page/test_training_page.py
TC_010.004.001
https://trello.com/c/W7q6pP2f/180-tc010004001-traning-block-1-block-promo-traning-main-visibility-verify-block-1-is-displayed
=> add test_Block1_is_displayed related to TC_010.004.001

locators/men_page_locators.py, pages/men_page.py, tests/test_men_page.py
=> TC_008.022.002 | Redirected to Bottoms page from Tops category in the left menu

tests/training_page/test_training_page.py
TC_010.004.002
https://trello.com/c/xedoCNld/181-tc010004002-traning-block-1-block-promo-traning-main-visibility-verify-block-1-consists-text
=> add test_Block1_text_is_displayed related to TC_010.004.002

pages/training_page/traning_page.py, tests/training_page/test_training_page.py
TC_010.004.003
https://trello.com/c/JFNSHnzG/182-tc010004003-traning-block-1-block-promo-traning-main-visibility-verify-the-size-of-block-1
=> add test_Block1_size_is_correct related to TC_010.004.003

pages/account/account_edit.py, tests/my_account/test__account_edit.py
TC_004.015.003 | Authorization > User's account > My account > Change password > Negative
https://trello.com/c/YZWDnenC/283-tc004015003-authorization-users-account-my-account-change-password-negative
=> test_change_password_negative

locators/base_page_locators.py, pages/main_page.py, tests/test_main_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;AwJL9jbu">TC_001.001.003 | Main page &gt; Self &gt;Verify the presence of image boxes on the main page</a></blockquote>
=> TC_001.001.003 | Main page > Self >Verify the presence of image boxes on the main page

tests/popular_search_terms/test_content_popular_search_terms_page.py
[TC_015.001.004](https://trello.com/c/n7nVYDch/269-tc015001004-popular-search-terms-content-verify-the-number-of-keywords-with-the-font-size-larger-than-88)
=> TC_015.001.004 | Popular Search Terms > Content > Verify there are at least 5 keywords with the font size larger than 88%

tests/men_page/test_men_category_page.py
[TC_008.014.002 | Men > Tops > Hoodies & Sweatshirts filter > The item is highlighted with a shadow](https://trello.com/c/J7wkqM4C)
=> test_item_is_highlighted

data/men_page_url.py, tests/men_page/test_men_category_page.py
[TC_008.014.004 | Men > Tops > Hoodies & Sweatshirts filter > Redirect to the product page by product image](https://trello.com/c/8V1oJWPf)
=> test_redirect_by_product_image

base/seleniumbase.py, locators/whats_new_page_locators.py, pages/other_pages/what_is_new.py, tests/what_is_new_page/test_what_is_new_page.py
TC_006.005.001
https://trello.com/c/H4dNM4vt/242-tc006005001-whats-new-page-search-a-sense-of-renewal-widget-visibility-clickability-redirection-verify-the-widget-title-text-mat
=> add test_widget_title_text 

locators/product_page_locators.py, tests/product_page/test_product_quantity.py
TC_002.014.001
https://trello.com/c/Fz9QccxF/345-tc002014001-product-page-main-info-quantity-choise-verify-the-product-quantity-is-displayed-on-the-page
=> Add test_product_quantity_is_displayed for TC_002.014.001

tests/men_page/test_men_category_page.py
[TC_008.014.005 | Men > Tops > Hoodies & Sweatshirts filter > Redirect to the product page by product title](https://trello.com/c/UySMVEVj)
=> test_redirect_by_product_title

pages/gear_page/category_page.py, pages/gear_page/gear_page.py, tests/gear_page/conftest.py, tests/gear_page/test_gear_page.py
moving back from any_page_precondition to gear_page_precondition... and some refactoring
=> refactoring gear page with step-like methods

tests/popular_search_terms/test_content_popular_search_terms_page.py
[TC_015.001.005](https://trello.com/c/yX7Q2XgJ/270-tc015001005-popular-search-terms-content-verify-among-the-keywords-with-the-enlarged-font-size-are-defined-words)
=> TC_015.001.005 | Popular Search Terms > Content > Verify among the keywords with the enlarged font size are defined words

locators/product_page_locators.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
TC_002.005.004 | Product page > Body > Main info > Availability 
https://trello.com/c/TloQADfu/220-tc002005004-product-page-body-main-info-availability
=> TC_002.005.004 | Product page > Body > Main info > Availability

data/popular_search_terms_page_data.py, tests/popular_search_terms/test_content_popular_search_terms_page.py
[Trello TC_015.001.006](https://trello.com/c/mbukt0Yl/271-tc015001006-popular-search-terms-content-verify-the-list-of-keywords-is-in-alphabetical-order-by-the-1st-character-of-a-keyword)
=> TC_015.001.006 | Popular Search Terms > Content > Verify the list of keywords is in alphabetical order by the 1st character

conftest.py, locators/base_page_locators.py, locators/checkout_page_locators.py, locators/item_page_locators.py, locators/order_and_payment_locators.py, pages/cart_page.py, pages/checkout_page.py, tests/guest/test_add_product_to_cart.py, tests/guest/test_guest_change_item_in_cart.py, tests/guest/test_guest_making_order_negative.py, tests/guest/test_guest_tabs_access.py
Added TC_004.001.002,3,5,6
TC_004.001.002,3,5,6 Also added some data to locators and pages files (without changing existing locators)
=> TC_004.001.002,3,5,6

data/men_page_url.py, tests/men_page/conftest.py, tests/men_page/test_men_category_page.py
[TC_008.017.001 | Men > Tops > Tees filter > Products are visible on the page](https://trello.com/c/fYg9TUBP)
=> test_product_are_visible

data/footer_urls.py, locators/base_page_locators.py, pages/checkout_page.py, tests/footer/test_verification_footer_elements.py, tests/guest/test_guest_footer_access.py, tests/guest/test_guest_making_order_negative.py, tests/guest/test_guest_making_order_positive.py, tests/guest/test_guest_sign_in_visibility.py
=> TC_004.001.004,6,7

tests/home_page/test_openpage_erin_recomends.py
=> test_openpage_erin_recomends

locators/base_page_locators.py, pages/eco_friendly/eco_friendly.py, pages/main_page.py, tests/test_main_page.py
TC_001.004.001
https://trello.com/c/X7cCj1Q5/235-tc001004001-main-page-search-eco-friendly-widget-clickability-verify-that-eco-friendly-widget-is-clickable
=> add test_main_page_eco_friendly_is_clickable

locators/item_page_locators.py, tests/product_page/test_first_color_choice.py
https://trello.com/c/JwekuVwF/395-tc002013001-product-page-main-info-color-choice-block-verify-user-can-choose-a-product-color
=> add: test color choice

pages/other_pages/eco_collection_new.py, tests/eco_collection_new_page/test_collection_page.py
TC _006.013.004 | Eco Collection New > The items name is visible and clickable
=> test/eco_collection_new_page/test_collection/def test_items

tests/men_page/test_men_category_page.py
[TC_008.017.003 | Men > Tops > Tees filter > Options appear on the product item](https://trello.com/c/SkTBtfpe)
=> test_options_appear_on_the_products

locators/base_page_locators.py, locators/checkout_page_locators.py, locators/my_account_page_locators.py, tests/my_account/test_my_account_visibility.py
=> TC.04.015_visibility

pages/men_category_page/category_page.py, tests/men_page/test_men_category_page.py
=> Test and page refactoring

conftest.py, locators/training_page_locators.py, tests/my_account/test_my_account_visibility.py, tests/training_page/test_training_page_logged_in.py
added test_training_page_logged_in.py file
=> test_training_page_logged_in

tests/training_page/test_training_page_logged_in.py
=> TC_010.redirections

locators/men_page_locators.py, pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
=> TC_008.005.002 | Tops page > Products >Verify a mode-switcher greed is Clickable

data/advanced_search_url.py, locators/advanced_search_locators.py, pages/advanced_search/advanced_search_form_page.py, tests/advanced_search/test_advanced_search.py
TC_017.002.001
https://trello.com/c/2HRJvgsl/587-tc017002001-advanced-search-results-search-results-contain-item-cards-verify-each-item-card-title-should-contain-the-search-quer
=> add test_advanced_search_results for TC_017.002.001

requirements.txt
=> added language-tool-python

locators/login_page_locators.py, pages/login/password_forgot.py, tests/login/test_password_forgot.py
=> ADD TC 004.007.009

Dockerfile
Thanks to @Alekmatv 
This part is needed for Allure and for hot fix the current issue with Language-tool-python lib.
=> Java has been added to Dockerfile

tests/popular_search_terms/test_visibility_and_clickability_of_keyword_links.py
[Trello TC_015.002.001](https://trello.com/c/SefIlVDh/595-tc015002001-popular-search-terms-visibility-and-clickability-verify-links-with-keywords-located-on-the-popular-search-terms-page)
[Trello TC_015.002.002](https://trello.com/c/bdgjHN2G/596-tc015002002-popular-search-terms-visibility-and-clickability-verify-keyword-links-leading-to-the-pages-with-the-keywords-are-cli)
=> Visibility And Clickability Of Links With Keywords On The Popular Search Terms Page

data/search_results_page_data.py, locators/popular_search_terms_page_locators.py, pages/popular_search_terms/popular_search_terms_page.py, tests/popular_search_terms/test_redirection_upon_click_on_keyword_links.py
[TC_015.003.001](https://trello.com/c/084JiSox/597-tc015003001-popular-search-terms-redirection-verify-redirecting-to-the-correct-page-upon-clicking-on-the-appropriate-keyword-lin)
=> TC_015.003.001 | Popular Search Terms > Redirection > Verify redirecting to the correct page upon clicking on the appropriate keyword link

data/search_results_page_data.py, tests/popular_search_terms/test_redirection_upon_click_on_keyword_links.py
[TC_015.003.002](https://trello.com/c/IRctRuAm/598-tc015003002-popular-search-terms-redirection-verify-the-title-of-the-new-page-upon-clicking-on-the-appropriate-keyword-link)
=> TC_015.003.002 | Popular Search Terms > Redirection > Verify the title of the new page upon clicking on the appropriate keyword link

locators/product_page_locators.py, tests/product_page/test_product_main_info.py
TC_002.016.002 Verify the display the "Add to wish list" element on the product page.
https://trello.com/c/bntEtbfX/294-tc002016002-product-page-main-info-add-to-wish-list-verify-the-display-the-add-to-wish-list-element-on-the-product-page
=> add test_add_to_wish_list_is_clickable for TC_002.016.002

locators/product_page_locators.py, tests/product_page/test_product_main_info.py
TC_002.016.001 | Verify clickable of the "Add to wish list" element on the product page.
https://trello.com/c/DzwUVfkG/247-tc002016001-product-page-main-info-add-to-wish-list-verify-clickable-of-the-add-to-wish-list-element-on-the-product-page
=> Add test_add_to_wish_list_is_clickable for TC_002.016.001

tests/product_page/test_product_main_info.py
TC_003.001.002 | Verify the redirect to the main page after clicking on the main logo.
https://trello.com/c/1IB9CWgz/248-tc003001002-header-logo-verify-the-redirect-to-the-main-page-after-clicking-on-the-main-logo
=> Add test_main_logo_redirect_to_main_page for TC_003.001.002

tests/men_page/conftest.py, tests/men_page/test_men_category_page.py
[TC_008.016.001 | Tops Page > select "Tees" > redirected to Tees Page](https://trello.com/c/jYYz0qAZ)
=> test_redirect_to_tees

data/test_urls_list.py, locators/base_page_locators.py, pages/header/header_page.py, tests/header/test_header.py
=> TC 003.002.001 Searchbar visibility

pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
=> TC_008.005.001 | Tops page > Products >Verify a mode-switcher "greed" is Visible

pages/footer/footer_page.py, tests/footer/test_footer.py
=> TC_012.012.001 | Footer > "Advanced search" link > Visibility

pages/footer/footer_page.py, tests/footer/test_footer.py
[TC] https://trello.com/c/wqD30522
=> TC_012.012.002 | Footer > "Advanced search" link > Clickability

.gitignore, conftest.py
=> Allure testing

locators/new_luma_yoga_collection_locators.py, pages/new_luma_yoga_collection_page/new_luma_yoga_collection_page.py, tests/new_luma_yoga_collection/conftest.py, tests/new_luma_yoga_collection/test_new_luma_yoga_collection.py
[TC_006_010_002](https://trello.com/c/cIthbewN/430-tc006010002-new-luma-yoga-collection-price-levels-verify-clickability-of-price-levels-in-the-price-tab)
[TC_006_010_001](https://trello.com/c/u3ZFTtOM/429-tc006010001-new-luma-yoga-collection-price-levels-verify-visibility-of-price-levels-in-the-price-tab)
=> New luma collection

locators/product_page_locators.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
TC_002.005.005 | Product page > Body > Main info > Size choice block
https://trello.com/c/KeXkJDUI/222-tc002005005-product-page-body-main-info-size-choice-block
=> Add TC_002.005.005

locators/product_page_locators.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
TC_002.005.006 | Product page > Body > Main info > Color choice block
https://trello.com/c/WvR1bGw9/225-tc002005006-product-page-body-main-info-color-choice-block
TC_002.005.007 | Product page > Body > Main info > Quantity choice
https://trello.com/c/RUsCgZRC/230-tc002005007-product-page-body-main-info-quantity-choice
=> Add TC_002.005.006, TC_002.005.007

locators/product_page_locators.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
TC_002.005.008 | Product page > Body > Main info > Add to Cart
https://trello.com/c/SEDkLxhj/231-tc002005008-product-page-body-main-info-add-to-cart
TC_002.005.009 | Product page > Body > Main info > Add to Wishlist
https://trello.com/c/UuqO4G7X/232-tc002005009-product-page-body-main-info-add-to-wishlist
TC_002.005.010 | Product page > Body > Main info > Add To Compare
https://trello.com/c/iBPGm2Hs/233-tc002005010-product-page-body-main-info-add-to-compare
=> Add TC_002.005.008,TC_002.005.009 and TC_002.005.010

data/search_results_page_data.py, locators/search_results_page_locators.py, pages/search_results_page/search_results_page.py, tests/popular_search_terms/test_redirection_upon_click_on_keyword_links.py
[Trello TC_015.003.003](https://trello.com/c/4E19gTgG/599-tc015003003-popular-search-terms-redirection-verify-the-heading-on-the-new-page-upon-clicking-on-the-appropriate-keyword-link)
=> TC_015.003.003 | Popular Search Terms > Redirection > Verify the heading on the new page upon clicking on the appropriate keyword link

locators/performance_sportswear_locators.py, pages/performance_fabrics/performance_sportswear.py, tests/performance_sportswear_page/test_performance_sportswear.py
=> ADD TC 006.012.001

data/performance_fabrics_url.py, tests/test_main_page.py
Verify a correct switch to the Shop Performance
https://trello.com/c/bk4tCdvj/246-tc001003002-main-page-search-shop-performance-widget-visibility-clickability-verify-a-correct-switch-to-the-shop-performance
=> Add test_correct_switch_to_shop_performance for TC_001.003.002

data/footer_data.py, locators/base_page_locators.py, pages/footer/footer_page.py, tests/footer/test_footer.py
[TC] https://trello.com/c/K9tJ8QMR
=> TC_012.012.003 | Footer > Advanced search link > Non-Clickability on Advanced Search Page

pages/advanced_search/advanced_search_form_page.py, tests/advanced_search/test_advanced_search.py
=> TC_016.004.001 | Advanced search > Verify the Search button is clickable

pages/advanced_search/advanced_search_form_page.py, tests/advanced_search/test_advanced_search.py
=> TC_016.004.002

pages/other_pages/what_is_new.py, tests/what_is_new_page/test_what_is_new_page.py
=> TTC _006.003.004

locators/men_page_locators.py, pages/men_category_page/category_page.py, tests/men_page/test_men_category_page.py
[TC_008.018.001 | Men > Tops > Tees filter > Clear all > Redirected to Tops page](https://trello.com/c/5rszSYV4)
=> test_redirect_after_clear

tests/popular_search_terms/test_footer_search_tearms_link.py
Thanks to Evgenii, just need to push this part to fix it and  step forward
=> Popular search fix - footer test

locators/men_page_locators.py, pages/men_category_page/category_page.py, tests/men_page/conftest.py, tests/men_page/test_men_category_page.py
[TC_008.034.001 | Men > Bottoms > Grid mode > Limit controller > Limit elements are displayed](https://trello.com/c/QTkGasOm)
=> test_grid_is_options_displayed

tests/my_account/test_my_account_editing.py
=> TC_004.015.016,017

tests/test_main_page.py
TC_001.004.002
https://trello.com/c/CRbWG3eE/237-tc001004002-main-page-search-eco-friendly-widget-visibility-that-widget-shop-eco-friendly-is-visible
=> test_main_page_eco_friendly_is_visible

data/men_page_url.py, locators/men_page_locators.py, pages/men_category_page/men_shorts_page.py, tests/men_page/test_men_shorts_page.py
TC_008.032.001
https://trello.com/c/Oaba8jq9/586-tc008032001-shorts-page-products-is-on-select-one-of-them-verify-the-visibility-and-selectability-of-one-of-product
=> add test_visibility_and_selectability_of_one_of_the_products related to TC_008.032.001

locators/login_page_locators.py, pages/login/login_page.py, tests/login/test_authorization.py
=> TC 004.002.005

locators/whats_new_page_locators.py, tests/what_is_new_page/test_new_in_womens_visible.py
[TC_006.001.001](https://trello.com/c/2L1jfzGK/203-tc006001001-whats-new-page-new-in-womens-user-is-able-to-see-section-new-in-womens) | What’s New page > NEW IN WOMEN’S > User is able to see section NEW IN WOMEN’S
=> TC_006.001.001 

pages/men_category_page/category_page.py, tests/men_page/test_men_category_page.py
[TC_008.034.003 | Men > Bottoms > Grid mode > Limit controller > Choosing of quantity displaying items on the page](https://trello.com/c/PVhkjTvf)
=> test_choosing_limit_option

locators/new_luma_yoga_collection_locators.py, pages/new_luma_yoga_collection_page/new_luma_yoga_collection_page.py, tests/new_luma_yoga_collection/test_new_luma_yoga_collection.py
+ [TC 003](https://trello.com/c/ywGgoXBD/431-tc006010003-new-luma-yoga-collection-price-levels-verify-ability-to-filter-the-page-by-price-level)
=> TC_006.010.003 + slightly updates

tests/men_page/test_men_category_page.py
[TC_008.034.004 | Men > Bottoms > List mode > Limit controller > Choosing of quantity displaying items on the page](https://trello.com/c/OTxLol3l)
=> test_list_choosing_limit_option

tests/my_account/test_new_account_header.py
[TC__004.003.009 | Authorization > check page title](https://trello.com/c/yarIW7zV/663-tc004003009-authorization-check-page-title)
=> TC__004.003.009

data/men_page_url.py, locators/men_page_locators.py, pages/men_category_page/men_tops_page.py, tests/men_page/test_jackets_images_click_redirects.py, tests/test_whatever_widget.py
Check clicking men's jackets images redirect to expected URLs (TC_008.004.010)
=> Checking men's jackets images redirect TC_008.004.010

locators/product_page_locators.py, pages/product_page/product_main_info.py, tests/product_page/test_product_main_info.py
TC_002.011.001 | Product page > Main info > Availability > In stock
https://trello.com/c/w6jDBhcX/387-tc002011001-product-page-main-info-availability-in-stock
=> TC_002.011.001 | Product page > Main info > Availability > In stock

data/whats_new_page.py, tests/what_is_new_page/test_new_in_womens_click.py
Updated links in Data folder
Created Test Suite for TC 006.001.002 - 006.001.007 'Click to categories in New in Women's section'
=> TC 006.001.002 - 006.001.007

tests/my_account/test_new_account_header.py, tests/wish_list_page_test/test_wish_list_page.py
Чуть изменил постоянно падающие тесты
=> [+] wait and driver fixture example fix

tests/advanced_search/test_advanced_search_functionality.py
[Trello TC_016.001.005](https://trello.com/c/0joj5fzY/664-tc016001005-advanced-search-functionality-verify-finding-a-product-upon-filling-out-one-of-the-fields-with-valid-data)
=> TC_016.001.005 | Advanced Search > Functionality > Verify finding a product upon filling out one of the fields with valid data

locators/men_page_locators.py, pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;o8Xz9w5Y">TC_008.005.003 | Tops page &gt; Products &gt;Verify a mode-switcher &quot;list&quot; is Visible</a></blockquote>
=> TC_008.005.003 | Tops page > Products >Verify a mode-switcher list is Visible

pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FUKs61Tf">TC_008.005.004 | Tops page &gt; Products &gt;Verify a mode-switcher &quot;list&quot; is Clicable</a></blockquote>
=> TC_008.005.004 | Tops page > Products >Verify a mode-switcher list is Clicable

locators/men_page_locators.py, pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yFNKqVQX">TC_008.005.005 | Tops page &gt; Products &gt;Verify view modes change (upon clicking modes-switcher &#39;List&#39;)</a></blockquote>
=> TC_008.005.005 | Tops page > Products >Verify view modes change

pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YzEJGVMH">TC_008.013.001 | Tops Page &gt; select &quot;Hoodies &amp; Sweatshirts&quot; &gt; Verify the link &#39;Hoodies&amp;Sweatshirts&#39; redirects to a correct page</a></blockquote>
=> TC_008.013.001 | Tops Page > select Hoodies&Sweatshirts > Verify the link Hoodies&Sweatshirts redirects to the correct page

data/men_page_url.py, locators/men_tops_page_locators.py, pages/men_category_page/men_tops_page.py, tests/men_page/test_men_tops_page.py
TC_008.004.004| Mens > Tops page > Product item >move to the Product page by clicking on the BTN “Add to Cart“ (acceptance criteria 5)
TC_008.004.002| Mens > Tops page > Product item >move to the Product page by clicking on the Product image (acceptance criteria 3)
TC_008.004.003| Mens > Tops page > Product item >move to the Product page by clicking on the Product name (acceptance criteria 4)
=> TC_008.004.002| TC_008.004.003| TC_008.004.004|  (US_008.004 acceptance criteria 3,4,5)

conftest.py, locators/men_page_locators.py, locators/product_page_locators.py, pages/men_page.py, tests/men_page/test_click_on_Add_to_cart.py, tests/men_page/test_men_tops_page.py, tests/men_page/test_men_tops_product_sorting.py, tests/men_page/test_tops_men_shopping_options.py, tests/my_account/test_add_to_cart_from_wish_list.py, tests/test_men_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;z5jv5VtP">TC_008.011.005 | Jackets page &gt;Verify inner-buttons are visable</a></blockquote>
=> TC_008.011.005 | Jackets page >Verify inner-buttons are visable

pages/men_page.py, tests/conftest.py, tests/guest/test__guest_add_address.py, tests/test_lumas_page.py, tests/test_main_page.py, tests/test_men_page.py, tests/test_whatever_widget.py, tests/training_page/test_training_page.py, tests/training_page/test_training_page_logged_in.py, tests/what_is_new_page/test_new_in_womens_click.py, tests/what_is_new_page/test_new_in_womens_visible.py, tests/what_is_new_page/test_saech_erin_recom.py, tests/what_is_new_page/test_what_is_new_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9dukbCmE">TC_008.011.002 | Jackets page &gt;Verify redirected to Item Page</a></blockquote>
=> TC_008.011.002 | Jackets page >Verify redirected to Item Page

data/men_page_url.py, locators/men_page_locators.py, pages/men_page.py, tests/order_and_payments/test_positive_order_and_payment.py, tests/product_page/test_first_color_choice.py, tests/product_page/test_product_main_info.py, tests/product_page/test_product_name_in_page_title.py, tests/product_page/test_product_page_body_structure.py, tests/product_page/test_product_page_structure.py, tests/test_men_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6LhTLgOF">TC_008.011.003 | Jackets page &gt;Verify redirected to Item Page(Click on Title)</a></blockquote>
=> TC_008.011.003 | Jackets page >Verify redirected to Item Page(Click on Title)

tests/gear_page/test_gear_page_evg.py
"""TC_009.005.001 | Gear page > categories > Verify opening the ‘Sprite Yoga Companion Kit’ page"""
"""TC_009.005.002 | Gear page > categories > Verify opening the 'Sprite Yoga Companion Kit' page after clicking on the "Shop Yoga Kit" button"""
-> I did not delete this two tests with bugs, I marked them in the parameterization
=> Test gear page

data/advanced_search_data.py, locators/advanced_search_results_locators.py, pages/advanced_search/advanced_search_results_page.py, tests/advanced_search/test_advanced_search_functionality.py
[Trello RF_000.003](https://trello.com/c/HIbXYnkf/690-rf000003-advanced-search-functionality-changing-test-tc016001005-due-to-add-new-page)
=> RF_000.003 | Advanced Search > Functionality > Refactoring test TC_016.001.005 due to add new page

data/advanced_search_results_data.py, locators/advanced_search_results_locators.py, pages/advanced_search/advanced_search_results_page.py, tests/advanced_search/test_advanced_search_functionality.py
[Trello TC_016.001.010](https://trello.com/c/z423GWa7/669-tc016001010-advanced-search-functionality-verify-data-search-results-match-to-entered-valid-data-after-clicking-on-the-search-bu)
=> TC_016.001.010 | Advanced Search > Functionality > Verify data search results match to entered valid data after clicking on the "Search" button

locators/advanced_search_locators.py, pages/advanced_search/advanced_search_form_page.py, tests/advanced_search/test_advanced_search.py
TC_017.006.001
https://trello.com/c/DfxJfJlU/658-tc017006001-advanced-search-results-item-cards-size-and-color-verify-clothes-items-have-size-and-color-options
=> add test_verify_clothes_items_have_size_and_color_options

locators/men_page_locators.py, pages/men_category_page/category_page.py, tests/men_page/test_men_category_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;v020obyW">TC_008.027.001 | Bottoms Page &gt;Verify all &quot;Shopping Options&quot; filters are clickable.</a></blockquote>
=> TC_008.027.001 | Bottoms Page >Verify all Shopping Options filters are clickable

locators/new_luma_yoga_collection_locators.py, pages/new_luma_yoga_collection_page/new_luma_yoga_collection_page.py, tests/new_luma_yoga_collection/test_new_luma_yoga_collection.py
[TC005](https://trello.com/c/GWAeNSFD/650-tc006010005-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-available-item-colors)
[TC004](https://trello.com/c/aDXA52Zq/649-tc006010004-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-images-and-names-of-items)
[TC006](https://trello.com/c/V31jYzQq/651-tc006010006-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-reviews-for-available-items)
=> TC_006.010.004-006

locators/men_page_locators.py, pages/men_page.py, tests/test_men_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;B8RrUKFX">TC_008.011.004 | Jackets page &gt;Verify the product card is highlighted with a shadow</a></blockquote>
=> TC_008.011.004 | Jackets page >Verify the product card is highlighted with a shadow

locators/advanced_search_locators.py, tests/advanced_search/test_advanced_search.py
TC_017.003.001
https://trello.com/c/a5sy2Ruc/641-tc017003001-advanced-search-results-modify-search-results-modify-your-search-link-is-visible-and-clickable
=> add TC_017.003.001 | Advanced Search Results > Modify search results\ ‘Modify your search’ link is visible and clickable

locators/men_tops_page_locators.py, pages/men_category_page/men_tops_page.py, tests/conftest.py, tests/men_page/test_men_tops_page.py
Mens > Tops page > Product item > Redirection to the My Wish List page by clicking on the heart-shaped BTN (acceptance criteria 6)
=> TC_008.004.005 Mens > Tops page > Product item > Redirection to the My Wish List page by clicking on the heart-shaped BTN (acceptance criteria 6)

base/seleniumbase.py, data/advanced_search_results_data.py, locators/advanced_search_results_locators.py, pages/advanced_search/advanced_search_results_page.py, tests/advanced_search/test_advanced_search.py
TC_017.006.002
https://trello.com/c/YNj595zK/659-tc017006002-advanced-search-results-item-cards-size-and-color-verify-clothes-items-should-be-modifiable-by-size
=> add test_test_enable_size_buttons related to TC_017.006.002

data/advanced_search_url.py, tests/advanced_search/test_advanced_search.py
TC 017.003.002
https://trello.com/c/GMKjktwK/680-tc017003002-advanced-search-results-modify-search-results-verify-redirection-to-the-advanced-search-form
=> TC 017.003.002 | Verify redirection to the 'Advanced Search' form

locators/item_page_locators.py
Code fix for https://trello.com/c/zf0bUJhQ/275-tc004001003-authorization-anonym-user-changing-item-in-the-cart
Trello card:
https://trello.com/c/APdixuIq/703-tc004001003-authorization-anonym-user-changing-item-in-the-cart-testguestchangeitemincart
=> fix:TC_004.001.003 test_guest_change_item_in_cart

tests/footer/test_verification_footer_elements.py
The devs added new copyright text that rendered the test failing
=> fix:TC_012.011.002 test_text_verification_of_the_copyright

locators/advanced_search_results_locators.py, pages/advanced_search/advanced_search_results_page.py, tests/advanced_search/test_advanced_search.py
TC_017.006.003
https://trello.com/c/QoMpPgG0/660-tc017006003-advanced-search-results-item-cards-size-and-color-verify-clothes-items-should-be-modifiable-by-color
=> TC_017.006.003 | Advanced Search Results > Item cards size and color > Verify clothes items should be modifiable by color

tests/gear_page/test_gear_page.py
Converting one check from test to final test step  + Updating Test data Generator
=> Gear page rafactoring

tests/advanced_search/test_advanced_search.py
TC_017.003.001
https://trello.com/c/a5sy2Ruc/641-tc017003001-advanced-search-results-modify-search-results-modify-your-search-link-is-visible-and-clickable
=> RF_TC_017.003.001_test_modify_your_search

tests/advanced_search/test_advanced_search.py
TC_017.006.004
https://trello.com/c/M7sJCgPU/661-tc017006004-advanced-search-results-item-cards-size-and-color-verify-clothes-items-should-be-modifiable-by-size-and-color
=> TC_017.006.004 | Advanced Search Results > Item cards size and color > Verify clothes items should be modifiable by size and color
